export const UPDATE_POKEMON_CARDS_LIST = "UPDATE_POKEMON_CARDS_LIST";
export const UPDATE_ALL_POKEMON_LIST = "UPDATE_ALL_POKEMON_LIST";
export const UPDATE_POKEMON_SEARCH_VALUE = "UPDATE_POKEMON_SEARCH_VALUE";
